name: CI Docker to GHCR

env:
  TARGET_NAME: unbound
  
  REGISTRY: ghcr.io
  CONTEXT: ${{ env.TARGET_NAME }}
  IMAGE_NAME: ${{ github.repository_owner	}}/${{ env.TARGET_NAME }}
  

on:
  push:
    # Update on change to master
    branches: 
    - master
    # Only update when correct Dockerfile is changed
    paths:
    - '${{ env.TARGET_NAME }}'
    
  schedule:
    # Update every Monday
    - cron: '39 7 * * 1'
  
  workflow_dispatch:
  


jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTEXT }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
