name: 'unbound: Docker CI'

env:
  CONTEXT: unbound

  GH_IMAGE_NAME: ${{ github.repository_owner }}/unbound
  DH_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/unbound
  

on:
  push:
    # Update on change to master
    branches: 
    - master
    # Only update when correct Dockerfile is changed
    paths:
    - 'unbound/**'
    
  schedule:
    # Update every Monday
    - cron: '39 7 * * 1'
  
  workflow_dispatch:
  


jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ env.GH_IMAGE_NAME }}
            ${{ env.DH_IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=edge
            type=raw,value={{date 'YYYYMMDD'}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.CONTEXT }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
